const express = require("express")
const router = express.Router()

const appointmentRoutes = require("./appointmentRoutes");
const patientRoutes = require('./patientRoutes')
const adminStatusRoutes = require("./administrativeStatusRoutes")
const medicalStatusRoutes = require("./medicalStatusRoutes")
const surgeryRoutes = require("./surgeryRoutes")
const medicRoutes = require("./medicRoutes")
const cashMovementLabelRoutes = require("./cashMovementLabelRoutes")
const cashMovementRoutes = require("./cashMovementRoutes")
const cashBoxRoutes = require("./cashBoxRoutes")
const mainBoxRoutes = require("./mainBoxRoutes")
const practiceRoutes = require("./practiceRoutes")
const healthInsuranceRoutes = require("./healthInsuranceRoutes")
const accountingLedgerRoutes = require("./accountingLedgerRoutes")
const stampRoutes = require("./stampRoutes")
const budgetRoutes = require("./budgetRoutes")
const utilsRoutes = require("./utilsRoutes")
const studyRoutes = require("./studyRoutes")
const studyOrderRoutes = require("./studyOrderRoutes")
const studyOrderStatusRoutes = require("./studyOrderStatusRoutes")
const studyOrderItemRoutes = require("./studyOrderItemRoutes")
const studyOrderItemStatusRoutes = require("./studyOrderItemStatusRoutes")
const surgeryAppointmentsRoutes = require("./surgeryAppointmentsRoutes")
const userRoutes = require("./userRoutes")
const { verifyToken } = require("../middlewares/authMiddleware")

const test = require("./test")

router.use('/appointments', verifyToken, appointmentRoutes)
router.use('/patients', verifyToken, patientRoutes)
router.use("/administrative-status", verifyToken, adminStatusRoutes)
router.use("/medical-status", verifyToken, medicalStatusRoutes)
router.use("/surgeries", verifyToken, surgeryRoutes)
router.use("/medics", verifyToken, medicRoutes)
router.use("/cash-movement/label", verifyToken, cashMovementLabelRoutes)
router.use("/cash-movement", verifyToken, cashMovementRoutes)
router.use("/cash-box", verifyToken, cashBoxRoutes)
router.use("/main-box", verifyToken, mainBoxRoutes)
router.use("/budget", verifyToken, budgetRoutes)
router.use("/practices", verifyToken, practiceRoutes)
router.use("/health_insurance", verifyToken, healthInsuranceRoutes)
router.use("/accounting-ledger", verifyToken, accountingLedgerRoutes)
router.use("/studies", verifyToken, studyRoutes) 
router.use("/study-order", verifyToken, studyOrderRoutes) 
router.use("/study-order-status", verifyToken, studyOrderStatusRoutes)
router.use("/study-order-item", verifyToken, studyOrderItemRoutes) 
router.use("/study-order-item-status", verifyToken, studyOrderItemStatusRoutes)
router.use("/surgery-appointments", verifyToken, surgeryAppointmentsRoutes)
router.use("/stamp", verifyToken, stampRoutes)

router.use("/utils", utilsRoutes)
router.use("/test", test)
router.use("/users", userRoutes)

module.exports = router