const express = require("express")
const router = express.Router()

const appointmentRoutes = require("./appointmentRoutes");
const patientRoutes = require('./patientRoutes')
const adminStatusRoutes = require("./administrativeStatusRoutes")
const medicalStatusRoutes = require("./medicalStatusRoutes")
const surgeryRoutes = require("./surgeryRoutes")
const medicRoutes = require("./medicRoutes")
const cashMovementLabelRoutes = require("./cashMovementLabelRoutes")
const cashMovementRoutes = require("./cashMovementRoutes")
const cashBoxRoutes = require("./cashBoxRoutes")
const dailySummaryRoutes = require("./dailySummaryRoutes")
const test = require("./test")
const userRoutes = require("./userRoutes")
const { verifyToken } = require("../middlewares/authMiddleware")

router.use('/appointments', verifyToken, appointmentRoutes)
router.use('/patients', verifyToken, patientRoutes)
router.use("/administrative-status", verifyToken, adminStatusRoutes)
router.use("/medical-status", verifyToken, medicalStatusRoutes)
router.use("/surgeries", verifyToken, surgeryRoutes)
router.use("/medics", verifyToken, medicRoutes)
router.use("/cash-movement/label", verifyToken, cashMovementLabelRoutes)
router.use("/cash-movement", verifyToken, cashMovementRoutes)
router.use("/cash-box", verifyToken, cashBoxRoutes)
router.use("/daily_summary", verifyToken, dailySummaryRoutes)
router.use("/test", test)
router.use("/users", userRoutes)

module.exports = router
